### ISSUE TITLE
Add option to set Clock font family

### ISSUE THREAD

**Issue by dangvd** [dangvd/ksmoothdock#102]

**Comment by dangvd** [comment]
Need a way to show QFontDialog without the size, because KSmoothDock calculates the size automatically depending on the dock's size and font size scaling option.

**Comment by dangvd** [comment]
Maybe use QFontComboBox instead.

**Comment by gzuaps** [comment]
Seems to be working for me .
Many Thanks.
GZU

**Comment by dangvd** [comment]
Thanks for confirming. I'll release a new version when #111 is done.

**Comment by dangvd** [comment]
Released in v6.2
