### ISSUE TITLE
Add Folders To Ksmooth Dock

### ISSUE THREAD

**Issue by 2635599** [dangvd/ksmoothdock#105]
just downloaded 6.0 to give it a run, and i'm loving the ease of use. how ever i want to place shortcuts for a few folders including the desktop to it. is this possible. thanks

**Comment by dangvd** [comment]
Hi,

Thank you!

As for shortcuts to folders, you can already do that. Right click on any program icon and select Edit Launchers. Then create a new launcher and set the appropriate command, for example:
dolphin Documents
for a shortcut to Documents folder.

Best,
Viet

**Comment by 2635599** [comment]
just followed your example above and get a error. i added a launcher, in the command box i entered "dolphin Documents" without the quotes and got "could not run command". this kind of stuff is exactly why i gave up on the various docks for linux cause where folders are concerned they typically are lacking, or certain icons that are on the you can't remove, and went to using a blank panel cause i could get exactly what i wanted. that said i'm running kubuntu 19.10 64 bit. cirrently i have shortcuts for my browsers and everything else removed from skmooth. what i want to add is desktop, and a folders/subfolders from my various other divers and partitions. thanks

**Comment by dangvd** [comment]
Did you click "Update" button after you entered the command?

**Comment by 2635599** [comment]
yes: what i'm doing.
rightclick dock
edit launchers
click add
name wanted
under command:  /home/gravedigger/Desktop/
click update
click apply
click on ok
click on new icon and get: could not run command: /home/gravedigger/Desktop/

**Comment by dangvd** [comment]
The command should be:
dolphin /home/gravedigger/Desktop/

Basically, if a command works from a terminal (e.g. Konsole), it should work with KSmoothDock.

**Comment by 2635599** [comment]
ok got it. thanks a lot, much appreciated. 

fyi liking the update. like the simple controls. didn't want or need a dock with tons of features. just something for a browsers, email, and my 5 or 6 most used folders. ksmooth fits the bill PERFECTLY. thanks again in helping me figure this out.

**Comment by 2635599** [comment]
ok looks like we have a issue with path length. i've entered the two paths below. the top one works and is 52 characters and the second one is 54. i click on the icon for tv series and get "The file or folder /home/gravedigger/Graves/Television/TV does not exist.".  if it's a issue with there being a space between TV and Series i'm not changing the folder name. i simply won't run the words together, cause the other folders i want to add are "Last Night's" and Last Episode" thoughts on a fix whichever the issue happens to be? thanks

dolphin /home/gravedigger/Graves/Downloads/Torrents/
dolphin /home/gravedigger/Graves/Television/TV Series/

  https://i.imgur.com/TW5DSbS.png

**Comment by dangvd** [comment]
It's not an issue with path length, but with the space in the path. It's easy to fix though, just put double quotes around the path. So in this case the command should be:
dolphin "/home/gravedigger/Graves/Television/TV Series/"

Cheers,
Viet

**Comment by 2635599** [comment]
oh ok COOL, thanks for the fix and **FAST** response. out of curiosity will that work for other areas of the os? i ask cause i got told in the past not to use spaces cause i might run into this issue? thanks again.

**Comment by dangvd** [comment]
You're welcome!

Yeah this (putting double quotes around paths with spaces) is quite standard and should work for other areas of the OS (and on Windows or Mac OS X) as well.

**Comment by 2635599** [comment]
ok cool and once again thanks, you have yourself a good one.
