### ISSUE TITLE
6.1 RC4 doesn't compile on Fedora 31

### ISSUE THREAD

**Issue by gzuaps** [dangvd/ksmoothdock#109]
Hi,

As in title 6.1 RC4 compilation fails in Fedora 31.
Dowloaded 6.1 from github after 6.0 failed also, see compilation output below

 [ 54%] Building CXX object CMakeFiles/ksmoothdock.dir/ksmoothdock_autogen/mocs_compilation.cpp.o
/bin/c++  -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_XML_LIB -I/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu -I/root/rpmbuild/BUILD/ksmoothdock-6.1/src -I/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu/ksmoothdock_autogen/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/KF5/KActivities -isystem /usr/include/KF5 -isystem /usr/include/KF5/KConfigCore -isystem /usr/include/KF5/KConfigGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/KF5/KDBusAddons -isystem /usr/include/KF5/KI18n -isystem /usr/include/KF5/KIconThemes -isystem /usr/include/KF5/KXmlGui -isystem /usr/include/KF5/KConfigWidgets -isystem /usr/include/KF5/KCodecs -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/KF5/KAuth -isystem /usr/include/KF5/KWindowSystem  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG   -Wall -Werror -fPIC -std=gnu++17 -o CMakeFiles/ksmoothdock.dir/ksmoothdock_autogen/mocs_compilation.cpp.o -c /root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu/ksmoothdock_autogen/mocs_compilation.cpp
[ 56%] Building CXX object CMakeFiles/ksmoothdock.dir/main.cc.o
/bin/c++  -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_XML_LIB -I/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu -I/root/rpmbuild/BUILD/ksmoothdock-6.1/src -I/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu/ksmoothdock_autogen/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/KF5/KActivities -isystem /usr/include/KF5 -isystem /usr/include/KF5/KConfigCore -isystem /usr/include/KF5/KConfigGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/KF5/KDBusAddons -isystem /usr/include/KF5/KI18n -isystem /usr/include/KF5/KIconThemes -isystem /usr/include/KF5/KXmlGui -isystem /usr/include/KF5/KConfigWidgets -isystem /usr/include/KF5/KCodecs -isystem /usr/include/KF5/KWidgetsAddons -isystem /usr/include/KF5/KAuth -isystem /usr/include/KF5/KWindowSystem  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG   -Wall -Werror -fPIC -std=gnu++17 -o CMakeFiles/ksmoothdock.dir/main.cc.o -c /root/rpmbuild/BUILD/ksmoothdock-6.1/src/main.cc

AutoMoc subprocess error
------------------------
The moc process failed to compile
  "/root/rpmbuild/BUILD/ksmoothdock-6.1/src/utils/command_utils_test.cc"
into
  "/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu/command_utils_test_autogen/include/command_utils_test.moc".

Command
-------
/usr/lib64/qt5/bin/moc -I/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu -I/root/rpmbuild/BUILD/ksmoothdock-6.1/src -I/usr/include/qt5 -I/usr/include/qt5/QtTest -I/usr/include/qt5/QtCore -I/usr/lib64/qt5/mkspecs/linux-g++ -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtWidgets -I/usr/include/KF5/KActivities -I/usr/include/KF5 -I/usr/include/KF5/KConfigCore -I/usr/include/KF5/KConfigGui -I/usr/include/qt5/QtXml -I/usr/include/KF5/KCoreAddons -I/usr/include/KF5/KDBusAddons -I/usr/include/KF5/KI18n -I/usr/include/KF5/KIconThemes -I/usr/include/KF5/KXmlGui -I/usr/include/KF5/KConfigWidgets -I/usr/include/KF5/KCodecs -I/usr/include/KF5/KWidgetsAddons -I/usr/include/KF5/KAuth -I/usr/include/KF5/KWindowSystem -I/usr/include -I/usr/include/c++/9 -I/usr/include/c++/9/x86_64-redhat-linux -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-redhat-linux/9/include -I/usr/local/include -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_NO_DEBUG "-DQT_TESTCASE_BUILDDIR=\"/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu\"" -DQT_TESTLIB_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB --include /root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu/command_utils_test_autogen/moc_predefs.h -o /root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu/command_utils_test_autogen/include/command_utils_test.moc /root/rpmbuild/BUILD/ksmoothdock-6.1/src/utils/command_utils_test.cc

Output
------
usr/include/c++/9/bits/fs_fwd.:39: Parse error at "std"

make[2]: *** [CMakeFiles/command_utils_test_autogen.dir/build.make:61: CMakeFiles/command_utils_test_autogen] Error 1
make[2]: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
make[1]: *** [CMakeFiles/Makefile2:621: CMakeFiles/command_utils_test_autogen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
[ 56%] Built target application_menu_config_test_autogen
make[2]: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
make[2]: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
[ 56%] Built target desktop_selector_test_autogen
[ 56%] Built target add_panel_dialog_test_autogen
make[2]: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
make[2]: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
make[2]: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
[ 56%] Built target application_menu_settings_dialog_test_autogen
[ 56%] Built target multi_dock_model_test_autogen
[ 56%] Built target appearance_settings_dialog_test_autogen
make[2]: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
[ 56%] Built target edit_launchers_dialog_test_autogen
make[2]: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
[ 56%] Built target dock_panel_test_autogen
[ 57%] Linking CXX executable ksmoothdock
/usr/bin/cmake -E cmake_link_script CMakeFiles/ksmoothdock.dir/link.txt --verbose=1
/bin/c++  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNDEBUG  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -rdynamic CMakeFiles/ksmoothdock.dir/ksmoothdock_autogen/mocs_compilation.cpp.o CMakeFiles/ksmoothdock.dir/main.cc.o  -o ksmoothdock -Wl,-rpath,/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu: libksmoothdock_lib.so /usr/lib64/libKF5Activities.so.5.61.0 /usr/lib64/libKF5DBusAddons.so.5.61.0 /usr/lib64/libKF5XmlGui.so.5.61.0 /usr/lib64/libKF5WindowSystem.so.5.61.0 -lstdc++fs /usr/lib64/libKF5IconThemes.so.5.61.0 /usr/lib64/libKF5ConfigWidgets.so.5.61.0 /usr/lib64/libKF5ConfigGui.so.5.61.0 /usr/lib64/libKF5ConfigCore.so.5.61.0 /usr/lib64/libQt5Xml.so.5.12.5 /usr/lib64/libKF5I18n.so.5.61.0 /usr/lib64/libKF5Codecs.so.5.61.0 /usr/lib64/libKF5Auth.so.5.61.0 /usr/lib64/libKF5AuthCore.so.5.61.0 /usr/lib64/libQt5DBus.so.5.12.5 /usr/lib64/libKF5CoreAddons.so.5.61.0 /usr/lib64/libKF5WidgetsAddons.so.5.61.0 /usr/lib64/libQt5Widgets.so.5.12.5 /usr/lib64/libQt5Gui.so.5.12.5 /usr/lib64/libQt5Core.so.5.12.5 
make[2]: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
[ 57%] Built target ksmoothdock
make[1]: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
make: *** [Makefile:144: all] Error 2
make: Leaving directory '/root/rpmbuild/BUILD/ksmoothdock-6.1/x86_64-redhat-linux-gnu'
error: Bad exit status from /var/tmp/rpm-tmp.nWJpBf (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.nWJpBf (%build)

Regards and Thanks,
GZU

**Comment by omni6** [comment]
#106

**Comment by dangvd** [comment]
As per #106:
 
This seems to be an error with <filesystem> standard library on your compiler. Could you try compiling a very short C++ program using anything in <filesystem> and see if it works?
See: https://en.cppreference.com/w/cpp/header/filesystem

Not much I can do, I'm afraid. I need <filesystem> standard library for 6.x

**Comment by gzuaps** [comment]
Hi,
Is this a change/new requirement in 6.X as 5.15 compiles OK.
Regards,
GZU

**Comment by dangvd** [comment]
Yeah it's the addition of \<filesystem>\ standard library as a dependency. I'm investigating it, see #106

**Comment by dangvd** [comment]
Could you guys try to compile it again (with 6.1 RC5)? Should be fixed now.

**Comment by gzuaps** [comment]
Hi,
I can confirm that 6.1 RC5 compiles OK for Fedora 31.
Thanks,
GZY

**Comment by dangvd** [comment]
Thank you!

**Comment by dangvd** [comment]
Released in v6.1
