### ISSUE TITLE
Installing Iin Manjaro

### ISSUE THREAD

**Issue by 2635599** [dangvd/ksmoothdock#112]
do you by any chance have any instructions for getting ksmooth up and running in manjaro? thanks

https://forum.manjaro.org/t/issues-with-kde/113286/9

**Comment by dangvd** [comment]
Does the Arch package not work?

https://aur.archlinux.org/packages/ksmoothdock/

**Comment by mihanich** [comment]
just installed from aur. works normal. maybe try again?
