### ISSUE TITLE
change auto hide behaviour to always show ksmoothdock on desktop

### ISSUE THREAD

**Issue by librewish** [dangvd/ksmoothdock#115]
i think it would be great to add this behaviour to autohide.
or add another option that allows this behaviour.
when on desktop dock should always be visible.
other time ie when a window is fullscreen or touches the dock 
 ksmothdock should hide.
and come visible when we hit with cursor the edge of screen.

**Comment by dangvd** [comment]
Panel Visibility -> Windows Can Cover (i.e. Intellihide) should already do this.

**Comment by librewish** [comment]
no thats not behaviour i want.
i doesn't want windows can cover
i only want
dock to be visible on desktop in autohide.
