### ISSUE TITLE
Opening menu while having any window maximized resizes the window

### ISSUE THREAD

**Issue by mkrutov** [dangvd/ksmoothdock#120]
I run debian sid and have installed latest git ksmoothdock. 

Regardless of what is the configuration of ksmoothdock behaviour, I observer an improper behaviour of menu:

1) Open up a maximized window (let's say Firefox).
2) Try to open ksmoothdock menu.

Expected:
ksmoothdock menu opens on "top" of the Firefox window, so Firefox is behind it.

Actual:
ksmoothdock menu opens. Firefox window momentarily resizes to less then half a screen (so ksmoothdock menu is filling the area under it).

Screenie:
![Menu_half_screen.png](https://user-images.githubusercontent.com/48674477/88506345-0449ff80-cfda-11ea-883f-096b798246cb.png)

**Comment by dangvd** [comment]
Hi,

This is working as intended. With a translucent menu, it looks much better/easier to read on the desktop wallpaper rather than on some background application window.

If you don't like it, you can disable it by right clicking on the Application Menu - Settings.
