### ISSUE TITLE
deb file cannot be installed: error: cannot satisfy dependencies

### ISSUE THREAD

**Issue by Sadi58** [dangvd/ksmoothdock#122]
I downloaded the deb file from kde store, and tried to install it on Kubuntu 20.10, but got this message: Error: cannot satisfy dependencies

**Comment by dangvd** [comment]
Hi,
Did it say what dependencies?

**Comment by Sadi58** [comment]
@dangvd Sorry, it seems actully it was an error on the part of QApt Package Installer! ;-)
I was able to install it when I tried again in terminal: sudo dpkg -i ksmoothdock_6.2-1_amd64.deb
BTW, as a Latte Dock user, who was considering to use alternatively "KDE panel + some other dock" my first impression is that ksmoothdock should urgently need support Desktop Actions. It's an indispensable feature for me. For instance, I should also see links to User Folders and some other different locations as well as some other associated tools (KFind, Krusader etc.) when I right click Dolphin icon.
