### ISSUE TITLE
Unshare Appearance Settingsa

### ISSUE THREAD

**Issue by AlienProber** [dangvd/ksmoothdock#125]
I decided to add a second dock today with different appearance setting than my main dock only to find when I change the appearance setting for it they also get changed for my original dock. This behavior happens rather I select Add Panel or Clone Panel. Ksmoothdock is the first dock system that I have seen that does not have independent setting for each dock instance. Is there a way to correct this behavior? Or do you have plans to correct this behavior? Thanks

KSmoothDock 6.2-2
ArcoLinuxD Plasma Desktop latest ISO installed

**Comment by dangvd** [comment]
Hi,

It's an intended behaviour. When I implemented multiple dock feature, I did try having separate appearance settings but after testing, I decided that it was better to have a shared appearance setting.

It actually took more work to have a shared appearance setting btw.

Hope it made it clear.
Best,

**Comment by AlienProber** [comment]
Well then I guess it's Latte Dock for me unless you can point in to a fix for a issue I ran into. I have by default just one KSmoothDock on the right of the screen and the default Plasma panel along with a blank Plasma panel. The issue is the Icons on the blank panel are now too small after changing themes and I see no way to increase their size.  If you know of a fix or might be able to point me at someone who might have a fix that would be great. Thanks

**Comment by dangvd** [comment]
If it's a Plasma issue, I'm not the best person to ask, sorry.
