### ISSUE TITLE
Hiding dock , when window is maximized

### ISSUE THREAD

**Issue by alireza-amirsamimi** [dangvd/ksmoothdock#19]
Hello
Thanks for this nice dock!
I have a feature request.
Please add some extra options in settings for hiding dock , when window is maximized and ... . some thing like docky and plank and cairo-dock.
Thanks!
Do you have any plan for putting this application in AUR for arch linux? It's make installation easier :)

**Comment by dangvd** [comment]
Thanks.

Hiding: you mean auto-hide feature, i.e. the dock hides when you leaves it and it only activates when the user moves the mouse to that edge of the screen? If so KSmoothDock 4.x had it but I haven't ported it to 5.x yet. Will do at some point.

About packages for distros I don't have them yet but if someone creates them and send them to me I'll make them available.

**Comment by dangvd** [comment]
Autohide feature is tracked here https://github.com/dangvd/ksmoothdock/issues/20

**Comment by alireza-amirsamimi** [comment]
I await for hiding feature :)
We have a development team for [Persepolis Download Manager](https://github.com/persepolisdm/persepolis/) . we are developing a pyqt5 Download Manager . our team members create packages for distros . 
I suggest them for packaging your application , Because some of our member are "KDE Plasma 5.9" user :)

Another thing that i forgot to say:
Please create a .desktop file for your apllication :)

**Comment by dangvd** [comment]
In the previous versions of KSmoothDock people created packages for them so I'm sure if v5.x is useful someone will do. I might create Deb package as well although there're more important things to do now. I will create bug for .desktop file.

**Comment by dangvd** [comment]
Bug for .desktop file https://github.com/dangvd/ksmoothdock/issues/21

**Comment by dangvd** [comment]
I'm gonna close this bug. Anything else please open a new bug. And if you have some Arch package etc. feel free to send over. Thanks.
