### ISSUE TITLE
Implements a Task Manager

### ISSUE THREAD

**Issue by dangvd** [dangvd/ksmoothdock#3]
KSmoothDock 4.x had a taskbar. Things to consider if we implement one for KSmoothDock 5:
- KSmoothDock 4.x had a pager between launchers and taskbar. Without a pager it might be difficult to distinguish between launchers and tasks.
- Tasks might have low resolution icons which might not work well with zooming.

**Comment by dangvd** [comment]
Closing. KSmoothDock will stay as a launcher dock for now for simplicity and UX usability.

**Comment by dangvd** [comment]
Let's have a look when there's time.

**Comment by Ichigo85** [comment]
Hi! Just one suggestion, do you think you can show tasks only for the active kde activity?

**Comment by dangvd** [comment]
Hi,

It's easy to do itself, but I give quite low priority to activity-related issues. Personally I think activities are not necessary given we already have virtual desktops :) I don't use activities myself.

I might make it the default behaviour though, when I get to it.

**Comment by dangvd** [comment]
Released in v5.10
