### ISSUE TITLE
Icon order. Natural sorting

### ISSUE THREAD

**Issue by kogolbok** [dangvd/ksmoothdock#30]
Hello.
I have added many launchers to the dock, added numbers to make some order. But KsmoothDock places them in this order 1,10,11... and so on, not in natural way. Is there anything is possible to fix this?

**Comment by dangvd** [comment]
Hi,

I'm working on an Edit Launchers dialog that will make it much easier to order the items using drag-and-drop. See #10. It will be released in v5.3 in 1 - 2 week's time.

For now could you just name them in a way that alphabetically they form the order you like, for example, prefix the filenames with 1a, 1b, 1c, 2a, 2b, 2c and so on?

**Comment by kogolbok** [comment]
Ok, waiting for 5.3. I already named launchers by letters a,b,c,
Best wishes.

**Comment by dangvd** [comment]
Cool, I'm gonna close this issue then.
