### ISSUE TITLE
Create multiple docks

### ISSUE THREAD

**Issue by Ichigo85** [dangvd/ksmoothdock#39]
Hi!I like a lot this project, but I would like the possibility to create multiple indipendent docks for different sides of the monitor. For habit I use two different docks, one on the left and one on the right, with different applications on them. Is that easy to develop? 
Thank you

**Comment by dangvd** [comment]
Thanks!

Yes it's certainly doable. There are higher priority issues that I need to work on for the next version (5.5), but I will consider this in the versions after that (5.6 or 5.7).

**Comment by dangvd** [comment]
Looks like there are other issues (e.g. #1 #3) that I need to look into first, so I don't think I can look into this soon. Sorry about that.

**Comment by dangvd** [comment]
Hi Ichigo85,
This has been done and released in v5.8
Hope you like it.
