### ISSUE TITLE
Wallpaper for multiple monitors

### ISSUE THREAD

**Issue by andrecbarros** [dangvd/ksmoothdock#49]
OK, this is not an issue, it is a feature request.

Right now each wallpaper assigned to each virtual desktop is repeated to composed monitors, on my case, 2 monitors hooked to my main computer. I'm using the xinerama extension. It creates a larger desktop adding the resolution of each monitors (width1 + width2, height1+height2). Would be cool if you could assign to each monitor different wallpapers.

Anyway, no hurries and thank you for this nice dock.

**Comment by dangvd** [comment]
At the moment I don't have a multi-monitor PC with Plasma 5 to look at this, but I will do as soon as I have (I should have one in a few months's time).

Assigning Low Priority for now but I will increase priority when I can work on it.

**Comment by dangvd** [comment]
Released in v5.9

**Comment by andrecbarros** [comment]
Thanks. Will try it.
