### ISSUE TITLE
Add multiple monitor support

### ISSUE THREAD

**Issue by night-crawler** [dangvd/ksmoothdock#55]
Hi!

It looks like that I cannot place dock on my second screen now. Please, add this support to ksmoothdock.

Thank you!

**Comment by dangvd** [comment]
When you have multi screen, wouldn't it be better to have the dock on the first screen?

**Comment by night-crawler** [comment]
I think it depends on user's working preferences and layouts. Right now I have a layout where the left screen:0 is for docs/debug/etc, and the main working area set to screen:1. Since I don't use mouse acceleration, I have to move about 1920px to launch something.

But I think user should have a choice.

**Comment by dangvd** [comment]
Right, I see. Probably the best way to implement this would be:
- If the user has multiple screens, display a menu item on the context menu to set screen:
Screen -> Screen 1, Screen 2,... the same way Position menu item is displayed.

**Comment by night-crawler** [comment]
> display a menu item on the context menu to set screen:
Screen -> Screen 1, Screen 2

I think it should be good. Between this and then, what's about KDE's long-click move support?

**Comment by dangvd** [comment]
I think it's better to just do the above.

**Comment by dangvd** [comment]
This is fixed on repo now, so if you can compile KSmoothDock from source code, you can just pull in the repo version. I'll also release this in KSmoothDock v5.6 soon.

**Comment by dangvd** [comment]
Released in v5.6
