### ISSUE TITLE
Fix animation/appearance bug with right side attached dock in multiscreen

### ISSUE THREAD

**Issue by night-crawler** [dangvd/ksmoothdock#56]
When 2 monitor are splitted by ksmoothdock it has some a bit weird animation.
![____1](https://cloud.githubusercontent.com/assets/1235203/25776434/bec50936-32c6-11e7-9c84-2224c32620b7.gif)

**Comment by dangvd** [comment]
Setting the dock on the Right side of the first screen doesn't really work due to this bug #24
