### ISSUE TITLE
On Clicked animation

### ISSUE THREAD

**Issue by ghost** [dangvd/ksmoothdock#64]
Hello. Could you, please, implement on clicked icon animation or transition? Sometimes it's not clear, did I press the Icon, or missed.

P.s, Thank you for this wonderful dock.

**Comment by dangvd** [comment]
Hi,

When you click on a launcher icon, the mouse cursor will change to 'Wait Cursor' briefly to acknowledge the click. Is it not noticable?

I was also thinking about doing a glowing effect on click but haven't got to it yet.

Thanks for your support, btw.

**Comment by dangvd** [comment]
This has been done in version 5.10
