### ISSUE TITLE
dock on each monitor

### ISSUE THREAD

**Issue by ibigpapa** [dangvd/ksmoothdock#65]
I have a Multi-Monitor setup and would like to have the dock on each monitor instead of just one.  It'd be nice if the dock started the same on each monitor, and had the possibility of customization per screen.

**Comment by dangvd** [comment]
Hi,
I'll probably work on supporting multiple docks with their own settings soon, and that would do for you?

**Comment by ibigpapa** [comment]
Yeah Their own settings would be ideal.  Thought i find one the most irritating things about KDE panels is you have to configure it on each one.  I think there should be an option to clone settings from one dock to the other to speed configuration of multiple instances.

**Comment by dangvd** [comment]
Yeah I'll create an option to clone a dock when I get to it.

**Comment by ibigpapa** [comment]
Awesome

**Comment by dangvd** [comment]
Hi ibigpapa,
This has been done and released in v5.8
Hope you like it.
