### ISSUE TITLE
Dock affects maximum window sizes on other screens

### ISSUE THREAD

**Issue by ibigpapa** [dangvd/ksmoothdock#66]
When i maximize the windows on screens where the smooth dock is not located it has a band at the bottom it appears to maximizing to the same size Ksmooth dock is set on the other monitor.

![screenshot_ksmooth_dock](https://user-images.githubusercontent.com/694054/30866273-5e4095d8-a29e-11e7-853a-f9537c8de213.png)

**Comment by dangvd** [comment]
That's weird. I use multiple monitor as well and I don't have this bug on my system. What version of KDE Plasma are you using?

**Comment by ibigpapa** [comment]
I'm running KDE Plasma 5.8.something.  On Kubuntu 16.04.

**Comment by dangvd** [comment]
Umm I will try to see if I can reproduce it but at the moment I can't.

By the way, the font of the clock on your dock looks too big -- seems the current bounding (and automatic font size) calculation I did needs improvement there.

**Comment by ibigpapa** [comment]
Yes it helped when i downsized the bar from the defaults.  Granted still gets cut off.  Not a very big issue though.  Do you want me to submit a 2nd issue for the clock?

**Comment by dangvd** [comment]
I've created the 2nd issue here: #69
