### ISSUE TITLE
It's not issue, but PKGBUILD request

### ISSUE THREAD

**Issue by pavbaranov** [dangvd/ksmoothdock#7]
Feel free to use it: http://pastebin.com/xV0mjqTn 
It's PKGBUILD of ksmoothdock v5.0 for Arch (Manjaro and other Arch-based distros).

**Comment by dangvd** [comment]
Hi,

Thanks for helping.

Unfortunately I don't use any Arch distro so can't really use it. However, if you create an Arch package, feel free to send over.

Best,
Viet
