### ISSUE TITLE
Reserve space on screen

### ISSUE THREAD

**Issue by CatChaos** [dangvd/ksmoothdock#71]
Hello,

is it possible to reserve the space of the dock on the screen like e.g. cairo-dock does?
I would like to not get ksmoothdock overlapped by other windows or other windows overlapped by ksmoothdock.

**Comment by dangvd** [comment]
Sorry for slow response. Anyway, KSmoothDock already reserves the space of the screen like any other dock/desktop panel does, from version 1. For example, if you maximize your windows, they will not cover the dock. Did you not get this behaviour?

**Comment by mihanich** [comment]
Seems when space reserved - menus also reserve it. Can you please make overlay instead of resizing fullscreen exapnded apps?

**Comment by dangvd** [comment]
I implemented that because transparent menu works better (easier to read) on a wallpaper rather overlaying on top of a window. And it's automatically expands as soon as the application menu closes anyway. I might make it optional in the future though.

**Comment by dangvd** [comment]
For the point above, I'm gonna make it optional -- it will be tracked in #67.

**Comment by dangvd** [comment]
Closing, as the option for last point has been released in v5.9
