### ISSUE TITLE
Show dock on desktop and when window isn't full screen.

### ISSUE THREAD

**Issue by idoqo** [dangvd/ksmoothdock#76]
Hi, great job. I was thinking if it will be possible to have some sort of "intellihide" where the dock only appears if the current window is maximized. Like, if the current window doesn't cover the position where the dock is, the dock still shows similar to plank and cairo-dock's implementation. The current Autohide hides the dock entirely till you hover on that position. I also think this was the intention for #19 but it appears to have closed. Thanks for all that you do for ksmoothdock btw :+1:

**Comment by dangvd** [comment]
Hi, thanks for your comment!

About the "intellihide" feature, it has already been implemented in #62 (as "Windows Can Cover" visibility mode). I'll release a new version with it very soon.

**Comment by dangvd** [comment]
Released in v5.9

**Comment by idoqo** [comment]
Aye! Seen the update. Thanks for your work.

**Comment by dangvd** [comment]
You're welcome :) Glad you like it.
