### ISSUE TITLE
Fedora packages

### ISSUE THREAD

**Issue by rafaelmr2** [dangvd/ksmoothdock#93]
Hi,

I install on Fedora 29 and have to install the packages below (can you put in README?):

extra-cmake-modules kf5-plasma-devel qt5-devel kf5-kactivities-devel kf5-kdbusaddons-devel kf5-ki18n-devel kf5-kiconthemes-devel kf5-kxmlgui-devel kf5-kwidgetsaddons-devel kf5-kwindowsystem-devel 

Thanks,

**Comment by dangvd** [comment]
Thanks! I will update README and online documentation.

**Comment by dangvd** [comment]
Released in v5.12
