### ISSUE TITLE
Request: Option to stop Ksmoothdock being raised

### ISSUE THREAD

**Issue by ordric** [dangvd/ksmoothdock#99]
Would it be possible to impliment an option to keep Ksmoothdock below windows, so that when the mouse touches the edge of the screen, it doesn't raise the dock.

**Comment by dangvd** [comment]
Hi,

There is already an option in the Context (Right-click) Menu: Visibility -> Windows Can Cover. Is it not what you're looking for?

Viet

**Comment by ordric** [comment]
Yes, that works, but when the mouse hits the screen edge, the dock comes up over the window, even when that is set. I would like to see an option to stop this happening.

The attached video demonstrates what I would like an option to stop. 

[vokoscreen-2019-07-25_22-23-08.zip](https://github.com/dangvd/ksmoothdock/files/3433329/vokoscreen-2019-07-25_22-23-08.zip)

**Comment by dangvd** [comment]
It seems you don't want the zooming effect? In that case, you can disable the parabolic zooming by setting Maximum Icon Size the same as Minimum Icon Size.

Otherwise if the dock zooms below a window, it would look weird IMHO.

**Comment by ordric** [comment]
No, that isn't what I want at all. 
I want an option for the dock not to pop up over a window when the mouse touches the screen edge.
[vokoscreen-2019-07-26_16-02-49.zip](https://github.com/dangvd/ksmoothdock/files/3436303/vokoscreen-2019-07-26_16-02-49.zip)

Here is another video... I have moved Ksmoothdock to the top, and placed another launcher at the bottom. It is an old launcher and hasn't been updated in ages, which is why I no longer use it, but even though it quite frequently messes up the graphics, the one thing it doesn't do is suddenly appear over the window when the mouse touches the bottom of the screen. 

Now look at what happens when a window covers Ksmoothdock and the mouse approaches the edge of the screen... the dock pops up over the window. 

That is all I would like an option to stop happening.

**Comment by dangvd** [comment]
In this case, how would you activate the dock? You would have to minimize all active windows?

**Comment by ordric** [comment]
Yes, that is correct.
It is really the mouse hitting the edge of the screen and bringing it up when not wanted that is such a problem. Maybe an accompanying option of a hotkey (or mouse button combination) to bring it up would be a good idea as well. Something that makes bringing it up when wanted a more definite action rather than accidental.

**Comment by dangvd** [comment]
I see. Sure I will work on it.

**Comment by dangvd** [comment]
Fixed in Repo, will release soon. No hotkey for now though.

**Comment by dangvd** [comment]
By soon I mean next week, as there are a few more bugs I'd like to fix before the next release.

**Comment by ordric** [comment]
You're a star... Thanks!

**Comment by dangvd** [comment]
Released in v5.15.
You're welcome :) Thanks for raising the issue!
